provenance-io/p8e

- .github/workflows/release-build-publish.yml
As it currently stands we are pushing to docker `:latest` tag on prereleases.
> Don't push to latest tag on prereleases.

- p8e-api/src/main/kotlin/io/provenance/engine/service/EnvelopeService.kt
- p8e-api/src/test/kotlin/service/EnvelopeServiceTest.kt
find by executionUuid AND publicKey to ensure proper envelope is fetched when affiliates share p8e instance
> Fix envelope error mailbox delivery

- p8e-proto-internal/src/main/proto/p8e/common.proto
- p8e-util/src/main/kotlin/io/p8e/crypto/SmartKeySigner.kt
Retrieve public key from SmartKey and convert it to a Java security public key so that it can be usable within P8e.
https://app.clubhouse.io/figure/story/89541/retrieve-public-keys-from-smartkey
Wanted to push this small addition out, before pushing other larger ones.
> Get public key from SmartKey and convert to BC

- p8e-api/src/main/kotlin/io/provenance/engine/stream/EventStream.kt
- p8e-shared/src/main/kotlin/io/provenance/p8e/shared/util/MDC.kt
if there were network or other issues that caused an event stream restart, and those network issues also caused errors in the streamHistory logic, then the event stream websocket could end up connected multiple times, duplicating broadcasted events
> fix event stream duplication

- p8e-api-webservice/src/main/kotlin/io/provenance/p8e/webservice/controller/AffiliateController.kt
- p8e-api-webservice/src/main/kotlin/io/provenance/p8e/webservice/domain/ApiAffiliate.kt
- p8e-api-webservice/src/main/kotlin/io/provenance/p8e/webservice/repository/AffiliateRepository.kt
- p8e-api/src/main/kotlin/io/provenance/engine/grpc/v1/AffiliateGrpc.kt
- p8e-api/src/main/kotlin/io/provenance/engine/service/AuthenticationService.kt
- p8e-migration/sql/V67__Add_Auth_Public_Key_to_Affiliate.sql
- p8e-proto-internal/src/main/proto/p8e/affiliate.proto
- p8e-shared/src/main/kotlin/io/provenance/p8e/shared/domain/Affiliate.kt
- p8e-shared/src/main/kotlin/io/provenance/p8e/shared/service/AffiliateService.kt
Add the ability to auth against p8e-api with a auth public key. 
Motivation behind this change is to restrict the usage of private keys within the code base especially when adding a key management system where the private key is not easily accessible. Also, existing keys already serves a purpose throughout the entire system where adding an auth key relieves the security risks of P8e having to manage the private key and is now in the complete possession of the user when auth-ing against p8e-api.
> Add support for auth public key

- p8e-api/src/main/kotlin/io/provenance/engine/service/MailboxService.kt
Wrap a transaction around the affiliate service getting the signing keypair on errors.
> wrap transaction around affiliateservice gettting signing keypair

- p8e-api/src/main/kotlin/io/provenance/engine/service/ChaincodeInvokeService.kt
- p8e-api/src/main/kotlin/io/provenance/engine/util/ProvenanceProtoExtensions.kt
- allow envelope to properly error out when the chain rejects due to invalid scope specification id
- previously, this would result in an envelope getting stuck at ENVELOPE_CHAINCODE COMPLETE, when in fact there was an error
- batch.clear() was moved, but needs to be present in this case where we error the whole batch, otherwise we keep retrying the batch and shipping errors back indefinitely
> handle missing scope specification record gracefully

- p8e-migration/sql/V68__Update_Contract_Spec_Mapping_Index.sql
- the contract bootstrapping was relying on this index filtering out duplicate contract spec hashes for submission with scope specifications... however, now that the chain is actually checking the spec->contract mapping (https://github.com/provenance-io/provenance/pull/322), this will break scope specifications for contract jars containing multiple contracts
- adding in the provenance_hash (hash of the contract spec proto itself) to the unique index allows for this to work
> fix contract spec -> scope mapping for contract jars with multiple contracts

- p8e-api/src/main/kotlin/io/provenance/engine/config/Properties.kt
- p8e-api/src/main/kotlin/io/provenance/engine/service/ChaincodeInvokeService.kt
- p8e-api/src/main/kotlin/io/provenance/engine/service/ProvenanceGrpcService.kt
- p8e-api/src/main/resources/application-container.properties
* Default multiplier is 1.0, so this has no effect unless configured to do so
* Can set maximum number of gas multiples per day, default is 1000, count resets every 24 hours after startup time (just in-memory tracking, nothing fancy)
> Add optional gas multiplier config to allow for increased fee distribution

- p8e-api/src/main/kotlin/io/provenance/engine/grpc/interceptors/JwtServerInterceptor.kt
- p8e-api/src/main/kotlin/io/provenance/engine/grpc/observers/EnvelopeEventObserver.kt
- p8e-common/src/main/kotlin/io/p8e/grpc/Constant.kt
- Might be helpful in tracking down weird connection issues (i.e. determining if two different services are trying to watch with the same key/contract combo)
> get client ip in grpc interceptor and log on EnvelopeEventObserver connect

- p8e-api/src/main/kotlin/io/provenance/engine/batch/TxErrorReaper.kt
- p8e-api/src/main/kotlin/io/provenance/engine/stream/ScopeStream.kt
I Realized this is currently broken on the public chain, there are 7 txs sitting in test that need to be kicked via this error reaper
* Pulled over scope lookup via new chain scope_addr event attribute from ScopeStream
> update tx error reaper to properly fetch scope via address via grpc

- p8e-api-webservice/src/main/kotlin/io/provenance/p8e/webservice/service/KeyManagementService.kt
- p8e-api-webservice/src/main/resources/application-container.properties
- p8e-api-webservice/src/main/resources/application-development.properties
- p8e-api-webservice/src/main/resources/application-local.properties
- p8e-shared/src/main/kotlin/io/provenance/p8e/shared/config/Properties.kt
Need to add the group id when generating security objects for groups (affiliates) that either belong to prod or test
> Add group id when generating SmartKey keys

- p8e-sdk/src/main/kotlin/io/p8e/ContractManager.kt
The ability to load and execute requested (fragment) contracts was required.  This PR contains an overload to `loadContract` with this increased flexibility.
`p8e-sdk/src/main/kotlin/io/p8e/ContractManager.kt`
> added loadContract overload for finer control over contract object

- p8e-util/src/main/kotlin/io/p8e/crypto/Pen.kt
Leaving as a draft as there can be different resolutions.
After discussing with Pierce, it is highly possible that we received an invalid input from the stream. 
As the client side stacktrace shows that there was an attempt to build facts and it has been known that contracts are built with null facts:
```
at io.p8e.engine.ContractWrapper.toFactInstance(ContractWrapper.kt:132)
at io.p8e.engine.ContractWrapper.buildFacts(ContractWrapper.kt:105)
at io.p8e.engine.ContractWrapper.<init>(ContractWrapper.kt:29)
```
Thus receiving NPE at signature update time, when testing with HelloWorld contracts this error didn't come about.
Solutions:
1. Wrap the signature update as in this PR shows and let it error out eventually in the execution lifecycle.
2. Let the client know at this point P8e received …
> Fix for NPE signature

- p8e-api/src/main/kotlin/io/provenance/engine/service/ProvenanceGrpcService.kt
- p8e-api/src/main/kotlin/io/provenance/engine/util/ProvenanceProtoExtensions.kt
- fixes handling of events where scope specification not present in local p8e db (i.e. some other party)
> look up scope specification name on chain vs. db

- p8e-sdk/src/main/kotlin/io/p8e/async/Heartbeat.kt
We probably should just move this into main so it is present in future releases until we have figured out why sometimes reconnect seems to just hang. I don't think anyone has been reliably on the pre-release created from this branch
> add in temporary logging around client reconnect to track down where things are dying

- p8e-util/src/main/kotlin/io/p8e/crypto/SmartKeySigner.kt
Let SmartKey sign empty data, mirror what the java Signature class currently does, cause there are uses cases where data comes in as empty but still gets signed.
> Allow signing of empty data for SmartKey

- p8e-api/src/main/kotlin/io/provenance/engine/service/ChaincodeInvokeService.kt
- p8e-api/src/main/kotlin/io/provenance/engine/service/TransactionStatusService.kt
- p8e-api/src/main/kotlin/io/provenance/engine/stream/ScopeStream.kt
free specific scopes for further transactions, hopefully a more correct approach than just watching the block height and clearing all scope ids upon an increase in height. This should prevent the same scope from having a contract run on it in different transactions in the same block, which can cause events to remain unprocessed, due to the scope.lastEvent being used to look up envelopes based on execution uuid
> Ensure scope separate block

- p8e-api-webservice/src/main/kotlin/io/provenance/p8e/webservice/config/Properties.kt
- p8e-api-webservice/src/main/kotlin/io/provenance/p8e/webservice/controller/ObjectController.kt
- p8e-api-webservice/src/main/resources/application-container.properties
- p8e-api-webservice/src/main/resources/application-development.properties
- p8e-api-webservice/src/main/resources/application-local.properties
- p8e-shared/src/main/kotlin/io/provenance/p8e/shared/domain/Envelope.kt
- p8e-shared/src/main/kotlin/io/provenance/p8e/shared/domain/Scope.kt
* The current envelope search mechanism usually times out in test, due to the inefficient query that was attempting to search all uuid columns. I changed this search (in the UI as well) to have a specific uuid searched for so the uuid indexes can be utilized. The other solution would be to have a composite index I think, but I tried creating one of these in test to see if it would help the explain, and it was taking forever, so I decided to just go this route instead. This is to help Peter find the state of things in test when he needs to
* Matt requested that we find a way to lock down access to the PII in the UI in prod some more, so I added a flag to just disable that endpoint altogether. Since we are not sure what the UI's role will be with the new client sdk anyways, this is the …
> Improve search and allow for disabling object fetching

- p8e-api-webservice/src/main/kotlin/io/provenance/p8e/webservice/controller/ObjectController.kt
- I believe this was causing the webservice to have one contract manager running per time the object fetch endpoint was called :facepalm:
- Side note: object fetch definitely doesn't work for SmartKey affiliates, since we have no way of grabbing the private key... but I knew that already and with the new client sdk, I don't think it matters
> Close down contract manager after fetching object

- p8e-api/src/main/kotlin/io/provenance/engine/config/Properties.kt
- p8e-api/src/main/kotlin/io/provenance/engine/service/ChaincodeInvokeService.kt
- p8e-api/src/main/kotlin/io/provenance/engine/service/TransactionStatusService.kt
- p8e-api/src/main/resources/application-container.properties
- to prevent transactions from getting stuck in the mempool of a node for whatever reason (usually gas related)
- tested with a positive timeout height of 12 and transactions completed normally, tested with a negative height and transactions were immediately rejected, not sure how to induce a stuck transaction locally
> set block height timeout on transactions

- os-client/src/main/kotlin/io/provenance/os/client/OsClient.kt
- os-proto/src/main/proto/objectstore/public_key.proto
- p8e-shared/src/main/kotlin/io/provenance/p8e/shared/domain/Affiliate.kt
- p8e-shared/src/main/kotlin/io/provenance/p8e/shared/service/AffiliateService.kt
The deployed version of object store appears to have this now, so it needs to be added in so the keys can be added via the ui again 🤞
> add signingPublicKey to object store key register request

- p8e-api/src/main/kotlin/io/provenance/engine/index/query/StringQuery.kt
- p8e-index-client/src/main/kotlin/io/p8e/index/client/query/StringQuery.kt
@jazzy-figure was needing a way to add in a not equals clause to a query and it turns out we don't support that. You can do it through the 'elasticsearch' versions of the query endpoints, but those don't support the pagination that the regular query endpoints do
> add in not equals string query option

- p8e-common/src/main/kotlin/io/p8e/grpc/client/ConnectionTimeoutInterceptor.kt
- p8e-common/src/main/kotlin/io/p8e/grpc/client/EnvelopeClient.kt
add interceptor to implement a connection timeout when connecting to the streaming event call
- Can't use a regular grpc deadline, since that can't be per-message and messages can be sent far into the future when the stream is open for a long time
Hopefully this fixes the occasional mysterious hang that locks up everything for client watchers
> Add connection timeout to streaming event call

- p8e-api/src/main/kotlin/io/provenance/engine/grpc/v1/IndexGrpc.kt
- p8e-api/src/main/kotlin/io/provenance/engine/service/ProvenanceGrpcService.kt
- p8e-api/src/main/kotlin/io/provenance/engine/stream/ScopeStream.kt
- Allows scopes that were created by new scope sdk to be queried properly via the old p8e
- This is an important piece of the los transition to the new sdk (since the final AssignToServicer contract requires scope sdk multiparty support to move that to the new sdk)
- Also prevent error resulting from incoming events that have no `lastEvent.executionUuid` set (i.e. scopes written by something other than the legacy p8e system, such as the new scope sdk, p8e doesn't need to do anything with these scopes anyways)
- Note: I went this route for fixing the query issue, rather than allowing incoming events w/o a last execution uuid from being inserted into the index_scope table and leaving the query alone, as the new scope sdk will write piecemeal record updates for existing scopes, so a …
> Query chain directly when fetching latest scope for IndexGrpc

- p8e-api/src/main/kotlin/io/provenance/engine/index/ProtoIndexer.kt
- no need to include the first consideration hash, as one class loader per jar is appropriate
- scopes with records written by the new sdk would end up with record groups referencing spec objects in object store that didn't have any 'considerationSpecsList', since the spec proto stored in OS has changed slightly and that is a reserved field now that will always be empty, this was leading to a NoSuchElementException when constructing the classLoaderKey using the `first()` call
> just use the jar hash for the classloader cache key

- p8e-api/src/main/kotlin/io/provenance/engine/service/EventService.kt
- p8e-api/src/test/kotlin/service/EventServiceTest.kt
- the retrial of 'dead' transactions (expired transactions that come back from the chain query as not found) was getting filtered out by the EventService, due to the 'transition' between ENVELOPE_CHAINCODE -> ENVELOPE_CHAINCODE not being listed as allowed
- Also added in an MDC fix for the event handler threads
> Fix chaincode retry state transition

- build.gradle
- p8e-api/build.gradle
- p8e-api/src/main/kotlin/io/provenance/engine/const/Versions.kt
- p8e-api/src/main/kotlin/io/provenance/engine/grpc/interceptors/JwtServerInterceptor.kt
- p8e-api/src/main/kotlin/io/provenance/engine/grpc/observers/EnvelopeEventObserver.kt
- p8e-common/src/main/kotlin/io/p8e/grpc/Constant.kt
- p8e-common/src/main/kotlin/io/p8e/grpc/client/ChallengeResponseInterceptor.kt
- p8e-proto-internal/src/main/proto/p8e/envelope.proto
- p8e-sdk/src/main/kotlin/io/p8e/ContractManager.kt
- p8e-sdk/src/main/resources/version.properties
- versions.gradle
- prevents ConnectionTimeoutInterceptor from timing out when an envelope isn't executed within the timeout window
- can only send this event when the client supports it (to avoid the watch dying due to 'unknown event type'), so I had to add some stuff in to send the p8e-sdk version as a GRPC header (could have sent an ENVELOPE_ACCEPTED event, but this seemed better)
> send an immediate event on client watch connect to force grpc headers through

- p8e-api/src/main/kotlin/io/provenance/engine/service/EnvelopeService.kt
- p8e-api/src/test/kotlin/helper/TestUtils.kt
- p8e-api/src/test/kotlin/service/EnvelopeServiceTest.kt
The ol' different signing/encryption keys strikes again!
Homepoint originator in prod has different signing/encryption/auth keys, and when the servicing affiliate rejected an envelope, the error failed to propagate back to the Homepoint originator, since the incoming mail public key is the encryption key, while the envelope table key is the signing key. This ensures the correct key is used when processing incoming mail
- ensures correct key is used for envelope lookup, preventing error from being dropped
> look up signing key via AffiliateService when erroring envelope

- p8e-api-webservice/build.gradle
- p8e-api/build.gradle
- We should **not be affected** since:
- We use the default Springboot logback config
- We are on Java 11
- log4j-core doesn't appear on our classpath
- we use log4j-over-slf4j
But I am adding this just to be extra safe
> CVE-2021-44228 precaution

- os-client/src/main/kotlin/io/provenance/os/client/OsClient.kt
- os-client/src/main/kotlin/io/provenance/os/domain/inputstream/DIMEInputStream.kt
- os-client/src/main/kotlin/io/provenance/os/util/Util.kt
- p8e-api/src/main/kotlin/io/provenance/engine/grpc/v1/ObjectGrpc.kt
- p8e-common/src/main/kotlin/io/p8e/definition/DefinitionService.kt
- p8e-common/src/main/kotlin/io/p8e/engine/extension/ProtoExtension.kt
- p8e-encryption/src/main/kotlin/io/provenance/p8e/encryption/aes/ProvenanceAESCrypt.kt
- p8e-encryption/src/main/kotlin/io/provenance/p8e/encryption/dime/ProvenanceDIME.kt
- p8e-proto-internal/src/main/proto/p8e/common.proto
- p8e-sdk/src/main/kotlin/io/p8e/client/EngineClient.kt
- p8e-sdk/src/main/kotlin/io/p8e/proxy/PermissionUpdater.kt
- p8e-sdk/src/test/kotlin/io/p8e/proxy/PermissionUpdaterTest.kt
- p8e-util/src/main/kotlin/io/p8e/util/Extensions.kt
- scope records written with the p8e-scope-sdk will be sha256 hashes, while this uses only sha512 hashes. When a scope record from p8e-scope-sdk was used as a contract input for a p8e-api contract, this would result in additional parties not being able to find facts in the scope, as they would have been loaded/decrypted/encrypted to new audience/saved under a sha512 hash that is different from the sha256 currently in the scope.
- This allows the scope facts re-saved by PermissionUpdater to be saved/permissioned in object store under the correct sha256 hash
- This functionality was brought over and slightly modified to be fully parameterized from p8e-scope-sdk
- The loHash functionality shouldn't be needed in p8e-api, but I brought it over in case there turns out to be a need with further …
> handle sha256/short hashes for interop w/ p8e-scope-sdk

- p8e-api/src/main/kotlin/io/provenance/engine/config/AppConfig.kt
- p8e-api/src/main/kotlin/io/provenance/engine/config/Properties.kt
- p8e-api/src/main/kotlin/io/provenance/engine/service/GasPriceService.kt
- p8e-api/src/main/kotlin/io/provenance/engine/service/ProvenanceGrpcService.kt
* Configuration properties to determine where to fetch gas price from, or what gas price to use (/as a fallback)
* Figure provides a gas price at https://test.figure.tech/figure-gas-price
* Will be a prod version as well soon, can be any url that returns json like below (gasPriceDenom _has_ to be `nhash` for now, or will be rejected and default will be used)
```
{
"gasPrice": 19050,
"gasPriceDenom": "nhash"
}
```
> configurable options for fetching/injecting gas price dynamically
